services:
  - type: web
    name: readygo-vite
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18
